spring:
  jpa:
    show-sql: true
  dubbo:
    application:
      name: bill-source
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 8086
      host: 127.0.0.1
    scan: com.cn


